relative-paths: true
models:
  - model.enzh.intgemm.alphas.bin
vocabs:
  - vocab.enzh.spm
  - vocab.enzh.spm
shortlist:
  - lex.50.50.enzh.s2t.bin
  - false
beam-size: 1
normalize: 1.0
word-penalty: 0.2
max-length-break: 128
mini-batch: 64
maxi-batch: 500
maxi-batch-sort: length
mini-batch-words: 512
workspace: 2000
max-length-factor: 2.5
gemm-precision: int8shiftAlphaAll

skip-cost: true
allow-unk: true
max-length: 500
